apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../base/kafka
  - ../base/mysql
  - ../base/podinfo
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
