---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-repo
  namespace: default
spec:
  interval: 5m0s
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-2
  namespace: default
spec:
  interval: 1m
  chart:
  spec:
    chart: nginx-ingress-2
    sourceRef:
      kind: HelmRepository
      name: nginx-repo
      namespace: default
    interval: 1m